### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by felciano** [KartikTalwar/mint#1]
I'm running into connection errors every time I try to run the tests. I've entered my username and password, after which I get:

```
raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='wwws.mint.com', port=443): Max retries exceeded with url: /loginUserSubmit.xevent (Caused by <class 'socket.error'>: [Errno 54] Connection reset by peer)
(mint)LUMACRFELCIANO:mint-master 
```

The offending line is line 21 in **init**.py:

```
response = self.session.post("https://wwws.mint.com/loginUserSubmit.xevent", data=payload).text
```

Any suggestions on how to debug? I've confirmed I can log in to the web UI wihtout any problems. Thanks!

**Comment by KartikTalwar** [comment]
@felciano would it be possible to know what version of `requests` you are using? At the time this lib was created, requests==2.0.1 and I just tested it with 2.3.0 and it seems to be working fine. Also, are you running these tests locally on your computer?

**Comment by felciano** [comment]
@KartikTalwar I just installed this so should all be recent libraries. I just confirmed pip installed requests 2.3.0 for me. And yes, running locally on a MacBook running Mavericks. Any suggestions on how to debug further? Is there a requests one-liner I can try to confirm the authentication and SSL are working?

**Comment by KartikTalwar** [comment]
Hmm, I wonder whats going on. The error itself implies that its passing through a proxy or the request payload/response is too big so the connection drops.
- What version of python are you using?
- Is your internet going through any proxy/vpn?
- Can you check it on a server somewhere?

Do you see the HTML returned when you login via this? can you paste the form HTML (the html will have a `<form>`) as a gist here (it doesn't contain any private info)?

``` py
import urllib
import urllib2

url = "https://wwws.mint.com/loginUserSubmit.xevent"
payload  = {
            "username" : EMAIL,
            "password" : PASSWORD,
            "task"     : "L",
            "nextPage" : "overview.event"
           }
post_data_encoded = urllib.urlencode(payload)

request_object = urllib2.Request(url, data)
response = urllib2.urlopen(request_object)
print response.read()
```

Then can you also modify the current code to print the response via requests and paste the form HTML

``` py
response = self.session.post("https://wwws.mint.com/loginUserSubmit.xevent", data=payload).text
print response # this line
```

**Comment by felciano** [comment]
Strange. The problem appears to be virtualenv related. The above test code works fine outside of a virtualenv, but inside a new virtual environment (no additional Pip packages installed) I run into the error.

Both indicate they are running Python 2.7.5, but with slightly different details. From within the virtualenv:

```
(deleteme)LUMACRFELCIANO:mint-master felciano$ python
Python 2.7.5 (default, Jun 17 2013, 23:25:56) 
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

whereas from a regular BASH prompty:

```
LUMACRFELCIANO:mint-master felciano$ python
Python 2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by KartikTalwar** [comment]
Strange indeed. Could you pass in the param to disable SSL verification and give it a shot?

http://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification

**Comment by felciano** [comment]
Looks like it must have been a misconfiguration on my end. I wiped my installed package and rebuilt my Python config as described in http://hackercodex.com/guide/python-development-environment-on-mac-osx/ and it now seems to work

**Comment by felciano** [comment]
Might have spoken too soon: the code no longer crashes, but it is not clear the I'm getting logged in correctly. In particular the hidden `javascript-token` field doesn't appear to be getting set. See https://gist.github.com/felciano/2eedc30c2be2e5124986#file-gistfile1-html.

Note that this happens both within and outside of the virtualenv

**Comment by KartikTalwar** [comment]
Glad to know that the socket err got resolved. I've been experiencing the 'cant login' problem since yesterday as well. For me, it logs you in every other try or so. Can you print the `js_token` in `login()` and run the script a couple of times to confirm you get logged in occasionally? I'll investigate that more on my end too

**Comment by felciano** [comment]
I'm actually just running the sample code you provided at https://github.com/KartikTalwar/mint/issues/1#issuecomment-45131756, and I can visual inspect the printed HTML, which always shows:

```
<input type="hidden" id="javascript-token" value=""/>
```

Can you confirm that if things are working correctly then we should see a real value there?

**Comment by felciano** [comment]
It just came through successfully, so you may be right re sporadic lack of authentication. I will test over the next day or so and report back.

**Comment by KartikTalwar** [comment]
Sounds good
